apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .serviceName }}
  template:
    metadata:
      labels:
        app: {{ .serviceName }}
    spec:
      containers:
        - name: {{ .container.name }}
          image: {{ .container.image }}
          ports:
            - containerPort: {{ .container.port }}

